name: CI

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL'
        required: true
        default: 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_30MB.mp4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install ffmpeg wget

      - name: Youtube Dl Setup
        run: sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl

      - name: Get file
        run: youtube-dl -o sample --recode-video flv "${{ github.event.inputs.url }}"

      - run: ffmpeg -re -stream_loop -1 -i sample.flv -deinterlace -vcodec libx264 -pix_fmt yuv420p -preset medium -r 30 -g 60 -b:v 2500k -acodec libmp3lame -ar 44100 -threads 6 -qscale 3 -b:a 712000 -bufsize 512k -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YT_KEY }}"
